import { useLocation } from "react-router-dom";

const partnerJourney = {
  affiliate: ["Complete your profile, identity documents and bank details. SPOTX reviews them before you can refer leads.", "Add a lead: a potential customer interested in SPOTX. Track whether the deal is in progress, won or lost.", "A won deal may earn a reward. Your earnings page shows the reward; Payments to You shows its payment status."],
  influencer: ["Complete your creator profile, identity documents and bank details.", "Connect your social accounts for review, then submit your post or reel links. Account review and content approval are separate checks.", "Approved paid content appears in Content Earnings. Payments to You shows when that money is paid."],
  vendor: ["Complete your profile, identity documents and bank details. SPOTX sets your individual commission terms.", "Invite customers with your referral link or add them yourself. Customers verify their email and manage their screens.", "Customer payments can earn you commission under your agreed terms. Customer payments and payments to you are shown separately."],
  reseller: ["Complete your profile and verification. Check your pricing and required advance payment before requesting licences.", "Request licences, wait for SPOTX approval, then assign them to customers. One licence allows one customer screen.", "Customers register their screens. You pay SPOTX's licence invoices; your customers pay you separately."]
};
const guides = [
  ["/partner/reseller/inventory", "Understand your screen licences", ["Bought: all licences added to your account. Ready to assign: bought licences that have not been assigned to a customer.", "Assigned: reserved for customers. Registered screens: devices customers have added. Active screens: devices currently enabled.", "SPOTX bills for bought licences according to your agreement, including licences you have not assigned yet."]],
  ["/partner/reseller/buy", "How to request more licences", ["Complete the required one-time advance payment first.", "Enter how many licences you need and submit the request. SPOTX reviews it before licences are added.", "An approved request is billed under your agreed billing schedule. Check the amount and terms before submitting."]],
  ["/partner/reseller/customers", "How to set up a customer", ["Add the customer's details or share your referral link.", "Assign screen licences to that customer from your available balance.", "The customer registers their screens. Assigned licences reserve capacity; they do not mean a screen is already active."]],
  ["/partner/reseller/billing", "Understand your bills", ["Each invoice shows what you owe SPOTX and its due date.", "Open the invoice to review its licences, tax and payment details before paying.", "A pending payment is not yet confirmed. Check the invoice status after payment before trying again."]],
  ["/partner/deals", "How leads become rewards", ["Add the potential customer's details and what they need.", "SPOTX reviews the lead and updates the deal. Won means the deal succeeded; pending means a decision is still needed.", "A reward appears in Referral Rewards when it is recorded. A won deal's value is not the amount paid to you."]],
  ["/partner/post-reel", "How content approval works", ["Submit the post or reel link from your social account.", "Waiting for review means SPOTX has not decided yet. If rejected, read the reason before submitting corrected content.", "Approved content earns money only when a payment rate applies. Check Content Earnings for the recorded amount."]],
  ["/partner/documents", "How identity review works", ["Upload the documents requested for your partner type. Use a clear PDF, JPG or PNG within the stated size limit.", "Waiting for review means SPOTX must check the document; you do not need to upload it again.", "If rejected, read the reason and replace the document with a corrected copy."]],
  ["/partner/bank", "How bank verification works", ["Enter the bank account where you want to receive money.", "Complete any verification payment requested on this page. This check is separate from receiving your earnings.", "Wait for review or correct the details if rejected. Review any change carefully before saving."]],
  ["/partner/commissions", "Understand your earnings", ["Each row shows a recorded reward, content payment or customer commission.", "The breakdown explains the amount and deductions. The related customer or deal value is separate from your earnings.", "The status shows whether it is still awaiting approval or payment. Use Payments to You for payment details."]],
  ["/partner/settlements", "Understand payments to you", ["This page tracks money SPOTX pays to you, rather than payments from customers.", "Open a payment to see the earnings included and any deductions.", "Pending or processing means payment is not complete. Paid means it has been recorded as paid; check your bank statement if needed."]],
  ["/admin/documents", "How to review identity documents", ["Open the document and compare its details with the partner profile.", "Approve only when the document is clear and matches. Otherwise reject with a specific correction the partner can make.", "Document approval is one part of verification. Check the partner profile for other required approvals."]],
  ["/admin/bank", "How to review bank details", ["Compare the account holder with the partner and inspect the verification result.", "Approve valid details or explain why they must be corrected. Use an override only after checking the reason carefully.", "A verified bank account does not mean a payout has happened. Payments to partners are managed separately."]],
  ["/admin/commissions", "How to manage partner earnings", ["Check which partner earned the amount and the linked deal, content or customer payment.", "Review the calculation before approving. Cancel or hold only when the reason is recorded clearly.", "Approved earnings and completed payments are different. Open Partner Payments to check whether money was paid."]],
  ["/admin/settlements", "How to manage payments to partners", ["Open the payment and review its earnings, deductions and supporting bill.", "Confirm the payment reference and amount before recording it as paid. Recording a payment does not itself make an offline bank transfer.", "Use the recorded status and reference to follow up on failed or pending payments."]],
  ["/admin/licence-payments", "How to check reseller payments", ["These are licence invoice payments from resellers to SPOTX.", "Check the invoice, due date and payment reference before recording or confirming payment.", "These payments are separate from commission payouts to partners."]],
  ["/admin", "How to review partner work", ["Use Partners to open the correct partner type and profile. The profile checklist shows what still needs approval.", "Read the submitted details and any supporting documents before approving. Add a clear reason when rejecting so the partner can correct it.", "Commission records what a partner earns. Partner Payments tracks money paid to them. Licence Payments tracks money resellers pay SPOTX."]],
  ["/reseller/customer", "How to use your screen account", ["Your reseller assigns the number of screens you can register.", "Open Screens to register a device within that allowance. Contact your reseller when you need more screens.", "You pay your reseller directly. This account shows your screen access, not payments to SPOTX."]],
  ["/customer", "How to use your customer account", ["Use Screens to add and manage your devices.", "Use Subscription to review your plan, screen allowance and dates before making changes.", "Use Billing to check recorded invoices and payments. A payment to SPOTX is separate from your vendor's commission."]]
];
export default function PageGuide({ partnerType }) {
  const { pathname } = useLocation();
  const found = guides.find(([prefix]) => pathname === prefix || pathname.startsWith(prefix + "/"));
  const steps = found?.[2] || partnerJourney[partnerType];
  if (!steps) return null;
  return <details key={pathname} className="mb-5 rounded-xl border border-slate-200 bg-white p-4 text-sm"><summary className="cursor-pointer font-semibold text-slate-800">{found?.[1] || "New here? See how your partner account works"}</summary><ol className="mt-3 list-decimal pl-5 space-y-2 text-slate-600">{steps.map(step => <li key={step}>{step}</li>)}</ol></details>;
}
